<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:macro name="aspen" params="prefix">

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931" />
    <xacro:property name="base_mass" value="6.0" /> <!-- arbitrary value for base mass -->
    <xacro:property name="base_width" value="0.34" />
    <xacro:property name="base_length" value="0.404" />
    <xacro:property name="base_height" value="0.13" />
    <xacro:property name="wheel_mass" value="0.3" /> <!-- arbitrary value for wheel mass -->
    <xacro:property name="wheel_len" value="0.045" />
    <xacro:property name="wheel_radius" value="0.085" />
    <xacro:property name="caster_wheel_mass" value="0.1" /> <!-- arbitrary value for caster wheel
    mass -->
    <xacro:property name="caster_wheel_radius" value="0.015" />
    <xacro:property name="z_offset" value="0.065" /> <!-- Space between drive wheels and bottom
    of chassis -->
    <xacro:property name="drive_wheel_x_offset" value="0.014" />

    <xacro:property name="drive_wheel_y_offset" value="0.0016" />

        <!-- Base Link -->
        <link name="${prefix}base_link">

        </link>

        <!-- Base footprint link -->
        <joint name="base_footprint_link" type="fixed">
            <parent link="base_link"/>
            <child link="base_footprint"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </joint>

        <link name="base_footprint">
        </link>


        <joint name="chassis_joint" type="fixed">
            <parent link="base_link" />
            <child link="chassis" />
            <origin xyz="${-base_length/2-drive_wheel_x_offset+wheel_radius} 0 ${z_offset}" />
        </joint>

        <link name="chassis">
            <visual>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}" />
                </geometry>
                <material name="orange" />
            </visual>

            <collision>
                <!-- <origin xyz="${-base_length/2-drive_wheel_x_offset+wheel_radius} 0 ${z_offset}" /> -->
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}" />
                </geometry>
            </collision>

            <xacro:inertial_box mass="6.0" x="${base_length}" y="${base_width}" z="${base_height}">
                <origin xyz="${base_length/2} 0 0.065" rpy="0 0 0"/>
            </xacro:inertial_box>
        </link>

        <!-- left wheel Joint -->
        <joint name="${prefix}left_wheel_joint" type="continuous">
            <parent link="${prefix}base_link" />
            <child link="${prefix}left_wheel" />
            <origin xyz="0 ${base_width/2-drive_wheel_y_offset} 0" rpy="-${pi/2}  0 0" />
            <axis xyz="0 0 1" />
        </joint>

        <!-- left wheel Link -->
        <link name="${prefix}left_wheel">
            <visual>
                <!-- <origin xyz="0 0 0" rpy="${PI/2} 0 0" /> -->
                <geometry>
                    <cylinder length="${wheel_len}" radius="${wheel_radius}" />
                </geometry>
                <material name="black" />
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_len}"/>
                </geometry>
            </collision>

            <xacro:inertial_cylinder mass="1.0" radius="${wheel_radius}" length="${wheel_len}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <!-- right wheel Joint -->
        <joint name="${prefix}right_wheel_joint" type="continuous">
            <parent link="${prefix}base_link" />
            <child link="${prefix}right_wheel" />
            <origin xyz="0 ${-base_width/2+drive_wheel_y_offset} 0" rpy="-${pi/2}  0 0" />
            <axis xyz="0 0 1" />
        </joint>

        <!-- right wheel Link -->
        <link name="${prefix}right_wheel">
            <visual>
                <!-- <origin xyz="0 0 0" rpy="-${PI/2} 0 0" /> -->
                <geometry>
                    <cylinder length="${wheel_len}" radius="${wheel_radius}" />
                </geometry>
                <material name="black" />
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_len}"/>
                </geometry>
            </collision>
            
            <xacro:inertial_cylinder mass="1.0" radius="${wheel_radius}" length="${wheel_len}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

<!-- Caster wheel -->
<joint name="caster_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="${-base_length+(0.170-0.018)} 0 0"/>
</joint>

<link name="caster_wheel">
    <visual>
        <geometry>
            <sphere radius="0.085"/>
        </geometry>
        <material name="black"/>
    </visual>

    <collision>
        <geometry>
            <sphere radius="0.085"/>
        </geometry>
    </collision>

    <xacro:inertial_sphere mass="0.2" radius="0.085">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_sphere>
</link>

    </xacro:macro>

</robot>