<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931" />
    <xacro:property name="base_mass" value="6.0" /> <!-- arbitrary value for base mass -->
    <xacro:property name="base_width" value="0.34" />
    <xacro:property name="base_length" value="0.404" />
    <xacro:property name="base_height" value="0.13" />
    <xacro:property name="wheel_mass" value="0.3" /> <!-- arbitrary value for wheel mass -->
    <xacro:property name="wheel_len" value="0.045" />
    <xacro:property name="wheel_radius" value="0.085" />
    <xacro:property name="caster_wheel_mass" value="0.1" /> <!-- arbitrary value for caster wheel
    mass -->
    <xacro:property name="caster_wheel_radius" value="0.015" />
    <xacro:property name="z_offset" value="0.065" /> <!-- Space between drive wheels and bottom
    of chassis -->
    <xacro:property name="drive_wheel_x_offset" value="0.014" />

    <xacro:property name="drive_wheel_y_offset" value="0.0016" />

    <joint name="laser_joint" type="fixed">
        <parent link="chassis" />
        <child link="laser_frame"/>
        <origin xyz="0 0 ${base_height-wheel_radius+0.025}" rpy="0 0 0"/>
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="0.035" length="0.053"/>
            </geometry>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="0.035" length="0.053"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="0.05" radius="0.035" length="0.053">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="laser_frame">
        <material>Gazebo/Black</material>

        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>
